language: java
sudo: required
dist: trusty
jdk:
  - openjdk8

install: true

services:
  - docker

addons:
  chrome: stable

before_script:
  - CHROME_MAIN_VERSION=`google-chrome-stable --version | sed -E 's/(^Google Chrome |\.[0-9]+ )//g'`
  - CHROMEDRIVER_VERSION=`curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_MAIN_VERSION"`
  - curl "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip" -O
  - "sudo apt-get install unzip"
  - "unzip chromedriver_linux64.zip"
  - "chmod +x chromedriver"
  - "sudo mv -f chromedriver /usr/local/share/chromedriver"
  - "sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver"
  - "sudo ln -s /usr/local/share/chromedriver /usr/bin/chromedriver"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

script:
  - mvn clean package -Dmaven.javadoc.skip=true -Dselenide.browser=chrome -Dwebdriver.chrome.driver=/usr/bin/chromedriver

after_success:
  - mvn coveralls:report
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=peneksglazami/chgk
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -f Dockerfile -t $REPO:$TAG .
  - docker push $REPO