language: java
jdk:
  - oraclejdk7

install: true

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

script:
  - mvn install -Dskip.unit.tests=true -Dmaven.javadoc.skip=true
  - mvn test

after_success:
  - mvn clean cobertura:cobertura coveralls:report