language: java
sudo: required
dist: trusty
jdk:
  - oraclejdk7

install: true

addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable

before_script:
  - "export CHROME_BIN=/usr/bin/google-chrome"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

script:
  - mvn clean
  - mvn install -Dskip.unit.tests=true -Dmaven.javadoc.skip=true -Dbrowser=chrome
  - mvn test -Dbrowser=chrome

after_success:
  - mvn clean cobertura:cobertura coveralls:report