language: java
sudo: required
dist: trusty
jdk:
  - oraclejdk7

install: true

addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable

before_script:
  - "sudo apt-get install unzip"
  - "wget -N http://chromedriver.storage.googleapis.com/2.21/chromedriver_linux64.zip"
  - "unzip chromedriver_linux64.zip"
  - "chmod +x chromedriver"
  - "sudo mv -f chromedriver /usr/local/share/chromedriver"
  - "sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver"
  - "sudo ln -s /usr/local/share/chromedriver /usr/bin/chromedriver"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

script:
  - mvn clean
  - mvn install -Dskip.unit.tests=true -Dmaven.javadoc.skip=true -Dbrowser=chrome -Dwebdriver.chrome.driver=/usr/bin/chromedriver
  - mvn test -Dbrowser=chrome -Dwebdriver.chrome.driver=/usr/bin/google-chrome

after_success:
  - mvn clean cobertura:cobertura coveralls:report