language: java
sudo: required
dist: trusty
jdk:
  - oraclejdk7

install: true

addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable

before_script:
  - "sudo apt-get install unzip"
  - "wget http://chromedriver.storage.googleapis.com/LATEST_RELEASE"
  - "read CHROMEDRIVER_LATEST_RELEASE < LATEST_RELEASE"
  - "wget -N http://chromedriver.storage.googleapis.com/$CHROMEDRIVER_LATEST_RELEASE/chromedriver_linux64.zip"
  - "unzip chromedriver_linux64.zip"
  - "chmod +x chromedriver"
  - "sudo mv -f chromedriver /usr/local/share/chromedriver"
  - "sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver"
  - "sudo ln -s /usr/local/share/chromedriver /usr/bin/chromedriver"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

script:
  - mvn clean cobertura:cobertura -Dmaven.javadoc.skip=true -Dselenide.browser=chrome -Dwebdriver.chrome.driver=/usr/bin/chromedriver

after_success:
  - mvn coveralls:report