language: java
sudo: required
dist: trusty
jdk:
  - openjdk8

install: true

services:
  - docker

addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable

before_script:
  - "sudo apt-get install unzip"
  - "wget -N http://chromedriver.storage.googleapis.com/2.38/chromedriver_linux64.zip"
  - "unzip chromedriver_linux64.zip"
  - "chmod +x chromedriver"
  - "sudo mv -f chromedriver /usr/local/share/chromedriver"
  - "sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver"
  - "sudo ln -s /usr/local/share/chromedriver /usr/bin/chromedriver"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

script:
  - mvn clean package -Dmaven.javadoc.skip=true -Dselenide.browser=chrome -Dwebdriver.chrome.driver=/usr/bin/chromedriver

after_success:
  - mvn coveralls:report
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=peneksglazami/chgk
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -f Dockerfile -t $REPO:$TAG .
  - docker push $REPO